### ISSUE TITLE
Question: Hooks vs Nested Components Performance?

### ISSUE THREAD

**Issue by osseonews** [commercelayer/commercelayer-react-components#274]
This is not a bug, just a question. I'm curious as to why you decided to go with a Nested Components type of architecture vs hooks? With hooks it seems like you can use a data fetching library like React Query or useSwr, and do away with some of the Context, making the codebase simpler and possibly more perfomant. I guess my worry is over scalability and performance. With the heavy use of Context here in nested components, is there any risk of performance issues as a site grows, since all the components will re-render upon state changes? Won't this slow a site down?

**Comment by acasazza** [comment]
Hi @osseonews, good question. Under the hood, we don't use Nested Components, we use hooks as you can see in our code. We don't expose our context out of the box at the moment, and we didn't develop a hooks library because of our fantastic API. As you can see using our components, we allow you to use a sort of templating of components. About the performance, it's our goal when we develop. Indeed, we use memo and callback hook when it's possible, and we do the best request to our API.
